# Generated by Django 3.2.19 on 2024-06-04 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicApi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('api_url', models.URLField()),
            ],
        ),
    ]
