# Generated by Django 3.2.19 on 2024-06-05 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0002_publicapi'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='use_api',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.DO_NOTHING, to='tasker.publicapi'),
            preserve_default=False,
        ),
    ]
